# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Difi < Formula
  desc "The pixel-perfect terminal diff viewer"
  homepage "https://github.com/xguot/difi"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xguot/difi/releases/download/v0.2.7/difi_Darwin_x86_64.tar.gz"
      sha256 "e8e50f931f3963c3efb372b64aee9e4bf9705b31bb5e384398f40e21491acc24"

      define_method(:install) do
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xguot/difi/releases/download/v0.2.7/difi_Darwin_arm64.tar.gz"
      sha256 "1917406844d472bd43675f8d3a1b16a4aea2505aea5a7df1fc7c237943f4acf3"

      define_method(:install) do
        bin.install "difi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xguot/difi/releases/download/v0.2.7/difi_Linux_x86_64.tar.gz"
      sha256 "59e7b804ce51ecfd13744075adf09378108698959e6af86abd2c0a3aa016c0dd"
      define_method(:install) do
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xguot/difi/releases/download/v0.2.7/difi_Linux_arm64.tar.gz"
      sha256 "92bd6b0bc9fe896174c186e0b3b951fd2fde40e182edac1fa1ab1703784f93fc"
      define_method(:install) do
        bin.install "difi"
      end
    end
  end
end
