# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Difi < Formula
  desc "The pixel-perfect terminal diff viewer"
  homepage "https://github.com/xguot/difi"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xguot/difi/releases/download/v0.2.2/difi_Darwin_x86_64.tar.gz"
      sha256 "5456fb674c7ab6ed3a2f081f1b15a9e41858679792ed73eff604b2a4a4b0b1d8"

      define_method(:install) do
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xguot/difi/releases/download/v0.2.2/difi_Darwin_arm64.tar.gz"
      sha256 "99b2375c1cc3b274851e39f818d973e0af62cd92edba407e9ca19d2de506bf70"

      define_method(:install) do
        bin.install "difi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xguot/difi/releases/download/v0.2.2/difi_Linux_x86_64.tar.gz"
      sha256 "b35a574f23a115f02c144b2539c6a1a771fd47d902f573afbbe02d0a78b8f845"
      define_method(:install) do
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xguot/difi/releases/download/v0.2.2/difi_Linux_arm64.tar.gz"
      sha256 "96d598cd922b2b6e44681468e234504cf0ea06b48dfd5aab955e74aa44c546a4"
      define_method(:install) do
        bin.install "difi"
      end
    end
  end
end
